name: Update readme

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci

      - name: Update svg
        env:
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
        run: node build-svg.js

      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'Auto updating readme'
          add: '*.svg'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
