name: Update readme

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 22

      - run: npm ci

      - name: Update svg
        env:
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
        run: node build-svg.js

      - name: Get current time
        uses: josStorer/get-current-time@v2.0.2
        id: current-time
        with:
          format: YYYY/MM/DD HH:mm
          utcOffset: '-05:00'

      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'update readme (${{ steps.current-time.outputs.formattedTime }}ET)'
          add: '*.svg'
